version: '3'

services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_CONNECTION_URL: ${DB_CONNECTION_URL}
    ports:
      - "5432:5432"

  fastapi:
    build:
      context: backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    command: "uvicorn main:app --reload --port=8000 --host=0.0.0.0"
    volumes:
      - ./backend:/app
    env_file:
      - .env
