version: '3'

services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: backend
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  fastapi:
    build:
      context: backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - ollama
    command: "uvicorn main:app --reload --port=8000 --host=0.0.0.0"
    volumes:
      - ./backend:/app
    env_file:
      - .env

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ./Modelfile:/Modelfile

