version: '3'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
    ports:
      - "5432:5432"

  fastapi:
    build: .
    ports:
      - "8000:8000"
    depends_on: 
      - postgres
    command: "uvicorn backend.main:app --reload --port=8000  --host=0.0.0.0"
    volumes:
      - .:/app
    env_file:
      - .env
