version: '3.7'

services:
  backend: 
    build: ./backend
    ports: 
      - 8000:8000
    environment:
      - POSTGRES_CONNECTION_URL=postgresql+psycopg2://postgres:postgres@0.0.0.0/backend
  database:
    image: postgres:15-alpine
    ports: 
      - 5432:5432
    volumes: 
    - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
    driver: local



